/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EpisodeEpisodeIdRouteImport } from './routes/episode.$episodeId'
import { Route as SavedShowPodcastIdRouteImport } from './routes/saved.show.$podcastId'

const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodeEpisodeIdRoute = EpisodeEpisodeIdRouteImport.update({
  id: '/episode/$episodeId',
  path: '/episode/$episodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedShowPodcastIdRoute = SavedShowPodcastIdRouteImport.update({
  id: '/show/$podcastId',
  path: '/show/$podcastId',
  getParentRoute: () => SavedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRouteWithChildren
  '/episode/$episodeId': typeof EpisodeEpisodeIdRoute
  '/saved/show/$podcastId': typeof SavedShowPodcastIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRouteWithChildren
  '/episode/$episodeId': typeof EpisodeEpisodeIdRoute
  '/saved/show/$podcastId': typeof SavedShowPodcastIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRouteWithChildren
  '/episode/$episodeId': typeof EpisodeEpisodeIdRoute
  '/saved/show/$podcastId': typeof SavedShowPodcastIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library'
    | '/profile'
    | '/saved'
    | '/episode/$episodeId'
    | '/saved/show/$podcastId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/library'
    | '/profile'
    | '/saved'
    | '/episode/$episodeId'
    | '/saved/show/$podcastId'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/profile'
    | '/saved'
    | '/episode/$episodeId'
    | '/saved/show/$podcastId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRoute
  ProfileRoute: typeof ProfileRoute
  SavedRoute: typeof SavedRouteWithChildren
  EpisodeEpisodeIdRoute: typeof EpisodeEpisodeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episode/$episodeId': {
      id: '/episode/$episodeId'
      path: '/episode/$episodeId'
      fullPath: '/episode/$episodeId'
      preLoaderRoute: typeof EpisodeEpisodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved/show/$podcastId': {
      id: '/saved/show/$podcastId'
      path: '/show/$podcastId'
      fullPath: '/saved/show/$podcastId'
      preLoaderRoute: typeof SavedShowPodcastIdRouteImport
      parentRoute: typeof SavedRoute
    }
  }
}

interface SavedRouteChildren {
  SavedShowPodcastIdRoute: typeof SavedShowPodcastIdRoute
}

const SavedRouteChildren: SavedRouteChildren = {
  SavedShowPodcastIdRoute: SavedShowPodcastIdRoute,
}

const SavedRouteWithChildren = SavedRoute._addFileChildren(SavedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRoute,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRouteWithChildren,
  EpisodeEpisodeIdRoute: EpisodeEpisodeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
